require 'rake/clean'
require 'redcarpet'

CLOBBER.include('site')

def markdown_convert(source_file, dest_file)
  markdown = Redcarpet::Markdown.new(
    Redcarpet::Render::XHTML,
    autolink: true)
  html = markdown.render(open(source_file).read)
  open(dest_file,'w').print(html)
end

directory 'site'

file 'site/index.html' => ['site','index.md'] do
  puts "Converting index.md"
  markdown_convert('index.md','site/index.html')
end

desc "Generate index.html"
task :index => 'site/index.html'
