desc "Say hello to everyone at Derailed TIMES # of times"
task :hello => :go_to_derailed do
  number_of_times = ENV['TIMES'] || 1
  number_of_times.to_i.times do
    puts "Hello!"
  end
end

desc "Go to the derailed meeting"
task :go_to_derailed => [:find_laptop, :get_in_car] do
  puts "Going to derailed!"
end

desc "get in the car with my laptop"
task :get_in_car => :find_laptop do
  puts "Getting in my car"
end

desc "Find my laptop"
task :find_laptop do
  puts "Finding my laptop"
end

task :default => :hello
