task :hello => :go_to_derailed do
  puts "Hello!"
end

task :go_to_derailed => [:find_laptop, :get_in_car] do
  puts "Going to derailed!"
end

task :get_in_car => 'find_laptop' do
  puts "Getting in my car"
end

task :find_laptop do
  puts "Finding my laptop"
end

