require 'rake/clean'
require 'rake/packagetask'

CLOBBER.include('site')
MARKDOWN_FILES = FileList['*.md']

Rake::PackageTask.new("site",:noversion) do |p|
  p.need_zip = true
  p.package_files.include("site/*")
end

task :markdown do
  markdown :generate_html, MARKDOWN_FILES, 'site'
  Rake::Task[:generate_html].invoke
end

desc "Generate html pages"
task :html => :markdown

